services:
  postgres:
    image: postgres:17
    container_name: goauth_postgres
    restart: always
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypwd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dockerDB/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql


volumes:
  pgdata:
