run:
  timeout: 3m
  tests: true  # Analyse également les fichiers *_test.go

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - gofmt
    - goimports
    - errcheck
    - ineffassign
    - unused
    - gosec
    - revive

linters-settings:
  gofmt:
    simplify: true

  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: indent-error-flow
      - name: blank-imports
      - name: dot-imports
      - name: var-naming
      - name: function-length
        arguments: [80]

  gosec:
    excludes:
      - G104

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

    - linters:
        - revive
      text: "should have comment"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
