name: Golang code quality

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    # ✅ 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # ✅ 2. Setup Go
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    # ✅ 3. Install golangci-lint
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/go/bin v1.55.2
        echo "$HOME/go/bin" >> $GITHUB_PATH

    # ✅ 4. Run golangci-lint
    - name: Lint code with golangci-lint
      working-directory: ./app
      run: golangci-lint run --config .golangci.yml